### ISSUE TITLE
add overschrijding hydra statistics

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares-research/kenmerkendewaarden#39]
Todo:
- [x] contributing guidelines: https://deltares-research.github.io/kenmerkendewaarden/CONTRIBUTING.html#add-your-contributions
- [x] Add HYDRA statistics for all stations (and document how/where to get these)
- [x] no hydra/vali data for stations other than HOEKVHLD (from KW-RMM project)

**Comment by Mares2022** [comment]
[HydraNL_kenmerkendewaarden_documentation.docx](https://github.com/user-attachments/files/16063656/HydraNL_kenmerkendewaarden_documentation.docx)

Documentation on how to extract data manually from Hydra-NL. The process is quite manual, and hopefully there is a way in the future to automate this process.

**Comment by veenstrajelmer** [comment]
The contents of the document were added as a new issue: https://github.com/Deltares-research/kenmerkendewaarden/issues/107
